kind: Pod
apiVersion: v1
metadata:
   name: testcontainer
   labels:
      Cloud: AWS
spec:
   containers:
     - name: testcontainer
       image: httpd
       ports:
        - containerPort: 80

    
